### ISSUE TITLE
Unable to upload save's server wide -- An unexpected server-side error has occurred!

### ISSUE THREAD

**Issue by Ma110w** [hzhreal/HTOS#3]
Running latest of everything, and [/ping returns ](https://github.com/user-attachments/assets/1ecfb00d-63b4-4ba3-9235-4bb7b8ec8483), my bot's scopes and permissions [look like this](https://github.com/user-attachments/assets/f926df9a-cf72-423b-b9ab-c5cf5893b291), and i aint got a clue what to do, because i cant find a wiki or troubleshooting for this anywhere, who knows, maybe im blind

![image](https://github.com/user-attachments/assets/f926df9a-cf72-423b-b9ab-c5cf5893b291)

![image](https://github.com/user-attachments/assets/1ecfb00d-63b4-4ba3-9235-4bb7b8ec8483)

**Comment by Ma110w** [comment]
so after realizing i didn't have discord nor discord.py installed in python, i installed them, and now my log prints a beautiful symphony of errors
```psnawp initialized
Traceback (most recent call last):
  File "M:\HTOS-1.1.0\HTOS-1.1.0\bot.py", line 5, in <module>
    from utils.constants import bot, TOKEN
  File "M:\HTOS-1.1.0\HTOS-1.1.0\utils\__init__.py", line 110, in <module>
    from .orbis import checkid, obtainCUSA, check_titleid, resign, reregion_write, obtainID, reregionCheck, checkSaves, OrbisError, handleTitles, SFO_MAGIC, SFO_VERSION, PARAM_NAME, SAVEDIR_RE, TITLE_ID_RE, ACCID_RE, SFOHeader, SFOIndexTable, SFOContextParam, SFOContext, validate_savedirname, parse_pfs_header, PfsSKKey, parse_sealedkey
  File "M:\HTOS-1.1.0\HTOS-1.1.0\utils\orbis.py", line 12, in <module>
    from data.crypto.mgsv_crypt import Crypt_MGSV
  File "M:\HTOS-1.1.0\HTOS-1.1.0\data\__init__.py", line 1, in <module>
    from data.cheats.common import QuickCheatsError, QuickCheats
  File "M:\HTOS-1.1.0\HTOS-1.1.0\data\cheats\__init__.py", line 3, in <module>
    from .gtav_cheats import Cheats_GTAV
  File "M:\HTOS-1.1.0\HTOS-1.1.0\data\cheats\gtav_cheats.py", line 9, in <module>
    from data.crypto import Crypt_Rstar as crypt
  File "M:\HTOS-1.1.0\HTOS-1.1.0\data\crypto\__init__.py", line 2, in <module>
    from .helpers import extra_decrypt, extra_import
  File "M:\HTOS-1.1.0\HTOS-1.1.0\data\crypto\helpers.py", line 5, in <module>
    from utils.helpers import DiscordContext, TimeoutHelper
  File "M:\HTOS-1.1.0\HTOS-1.1.0\utils\helpers.py", line 9, in <module>
    from discord.ext import pages
  File "C:\Users\seths\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\pages\__init__.py", line 10, in <module>
    from .pagination import *
  File "C:\Users\seths\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\pages\pagination.py", line 31, in <module>
    from discord.ext.bridge import BridgeContext
  File "C:\Users\seths\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\bridge\__init__.py", line 26, in <module>
    from .bot import *
  File "C:\Users\seths\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\bridge\bot.py", line 31, in <module>
    from discord.commands import ApplicationContext
  File "C:\Users\seths\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\__init__.py", line 26, in <module>
    from .context import *
  File "C:\Users\seths\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\context.py", line 69, in <module>
    class ApplicationContext(discord.abc.Messageable):
  File "C:\Users\seths\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\context.py", line 271, in ApplicationContext
    @discord.utils.copy_doc(Interaction.respond)
AttributeError: type object 'Interaction' has no attribute 'respond'. Did you mean: 'response'?```

**Comment by Ma110w** [comment]
After running "pip uninstall -r requirements" then "pip install -r requirements" it appears to work again, but as it stands i stil lam unable to actually upload files to the bot, and it still retains the same error from the first comment
![image](https://github.com/user-attachments/assets/4a9fe880-5fda-47d0-b92f-10af89a047a7)
